const articles =  [
    { id:1, title: "Today I spilt my coffee", createdAt:"Thursday, Mar 10, 2022", description:"Well that was a big oops. Everyone in the shop saw what happened. Can't get over it",comments: ["Hahaha that happened to me too!", "Don't worry about it"],reactions: ["U+1F600", "U+1F600"], giphys: "https://media.giphy.com/media/VCk24zfiG0It6uVzY7/giphy.gif"},
    { id:2, title: "Feeling happy", createdAt:"Friday, Mar 11, 2022", description:"Today's weather is really affecting my mood in a positive way. Hope it stays like this",comments: ["I love days like this.", "Bring on the sun!"],reactions:  [null], giphys: [null]},
    { id:3, title: "Need some ideas", createdAt:"Friday, Mar 11, 2022", description:"Anyone know any new recipes I could try using salmon?",comments: ["You could try putting it on the oven with some herbs, lemon and garlic", "Salmon! YUCK!"],reactions:  ["U+1F600"], giphys: [null]},
    { id:4, title: "Yeah baby!", createdAt:"Friday, Mar 11, 2022", description:"Just got a pay rise once again. I can really see my work paying off.",comments: ["Lucky you :( ", "Make sure you're still saving! Otherwise it will be pointless"],reactions: ["U+1F600", "U+1F600", "U+1F602"], giphys: [null]},
    { id:5, title: "Why every one should learn how to code",
    createdAt:"Monday, Mar 07, 2022", description:"Technology is everywhere in the modern world and continues to develop at an astonishing rate. Coding already plays a key part in this technological evolution and will become increasingly important in light of new robotics and automated technologies. Learning to code will give you the tools you need to go on and be part of shaping the future. This could include roles in RPA, building automated systems for global banks or healthcare organisations, or even helping to improve the tech in self-driving cars - this is just scratching the surface!",
    comments: ["Good post", "I like this post"],reactions: ["U+1F600", "U+1F600"], giphys: 'https://media.giphy.com/media/epHcSYCjKxWUgGAR1o/giphy.gif'},
    { id:6, title: "The art of self acceptance",
    createdAt:"Tuesday, Mar 08, 2022",
    description:"It is important to remind ourselves that no one is perfect.We all have strengths and weaknesses and we certainly possess the resources to work on improving ourselves.Each of us is unique and has specific talents and abilities to offer. We are all here, in the words of Walt Whitman, ‘to contribute a verse’.In order to appreciate yourself it is up to you to discover what makes you unique and to further develop those talents. We have a responsibility to ourselves to do so.You cannot sit around and wait for approval from others. Work on accepting yourself. You are the only ‘you’ t",
    comments: ["This is very helpful"],reactions:  [null], giphys: [null]},
    { id:7, title: "How to start a business",
    createdAt:"Wednesday, Mar 9, 2022",
    description:"Your first step in learning how to start a business is to identify a problem and solution. This is because successful startups begin from business ideas that fill the needs of a group of customers. But your idea doesn’t always have to be a new one. You can update existing products or services in a way that’s better for the consumer.For instance, Apple started from Steve Jobs’ original idea for a computer and has since created enhanced versions that better fit the market. They’ve also continued to evolve newer products like iPhones and iPads, making them more useful with each update.One example is how they’re adding a keyboard for iPads that’ll make them easier to use like a laptop.2 All these innovations by Apple led to them being worth of over a billion dollars. ",comments: [ "Not a bad post"],reactions:  ["U+1F600"], giphys: 'https://media.giphy.com/media/qFG4dgGE9qLUyKeHTS/giphy.gif'},
    { id:8, title: "why happiness matter", createdAt:"Thursday, Mar 10, 2022",
    description:"Happiness is more than a good feeling or a yellow smiley face. It's the feeling of truly enjoying your life, and the desire to make the very best of it. Happiness is the 'secret sauce' that can help us be and do our best.Besides feeling good, positive emotions do good things for our brains and bodies. They lower stress hormones, help ease anxiety and depression, and improve our immune system.Feeling some positive emotions every day has a big effect on our happiness and well-being. That's why it's so important to do things that give us positive feelings. Even simple actions like playing with a child or a pet or going for a walk outdoors can inspire these feelings.Knowing how to manage our negative emotions is also key to happiness. Difficult emotions are a fact of life. But the way we handle them makes all the difference.",
    comments: ["Great post! ", "I relate to this post"],reactions: ["U+1F600", "U+1F600", "U+1F602"], giphys: [null]}
]




module.exports = articles
